package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.57

import (
	"context"
	"fmt"

	"github.com/ariefsn/gembok/models"
)

// AuthCredentialsSignIn is the resolver for the authCredentialsSignIn field.
func (r *mutationResolver) AuthCredentialsSignIn(ctx context.Context, input models.AuthSignInPayload) (*models.AuthSignInResponse, error) {
	panic(fmt.Errorf("not implemented: AuthCredentialsSignIn - authCredentialsSignIn"))
}

// AuthProfile is the resolver for the authProfile field.
func (r *queryResolver) AuthProfile(ctx context.Context) (string, error) {
	panic(fmt.Errorf("not implemented: AuthProfile - authProfile"))
}
